#!/usr/bin/env perl
#
# This file is part of Zoe Assistant - https://github.com/guluc3m/gul-zoe
#
# Copyright (c) 2014 David Muñoz Díaz <david@gul.es> 
#
# This file is distributed under the MIT LICENSE
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

#
# Shows and executes all state-related commands
#

use Getopt::Long qw(:config pass_through);
use Env qw(ZOE_HOME);
use strict;

my $get;
my $run;
my $sender;
my $canonical;

GetOptions("get"                   => \$get,
           "run"                   => \$run,
           "msg-sender-uniqueid=s" => \$sender,
           "canonical=s"           => \$canonical);

exit unless $sender;

if ($get) {
  &get;
} elsif ($run) {
  &run;
}

#
# Lists the commands available in var/state/command/$sender
# These commands are generated by different agents using zoe.state.Command
#
sub get {
  my $dir = "$ZOE_HOME/var/state/commands/$sender";
  opendir (DIR, $dir) or die $!;
  while (my $file = readdir(DIR)) {
    print "$file\n" unless $file =~ /^\..*/;
  }
}


#
# Executes the command stored in var/state/commands/$sender/$canonical
# where $canonical is the matched command
#
sub run {
  local $/;  
  my $file = "$ZOE_HOME/var/state/commands/$sender/$canonical";
  open(FILE, $file);  
  my $document = <FILE>; 
  close (FILE);
  print "$document\n";
}

